# Generated by Django 5.2.7 on 2025-10-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cmd',
            field=models.CharField(blank=True, help_text='Command representation for the task', max_length=512),
        ),
    ]
